### ISSUE TITLE
Core seen while running "run instance sync" when remote backup calculation is enabled.

### ISSUE THREAD

**Issue by sachinites** [sachinites/SPFComputation#8]
**BT :** 

Program received signal SIGSEGV, Segmentation fault.
0x0807f521 in spf_computation (spf_root=0x0, spf_info=0x3224, level=LEVEL1, spf_type=FORWARD_RUN)
    at spfcomputation.c:748
748         if(IS_OVERLOADED(spf_root, level)){
(gdb) br
Breakpoint 1 at 0x807f521: file spfcomputation.c, line 748.
(gdb) bt
#0  0x0807f521 in spf_computation (spf_root=0x0, spf_info=0x3224, level=LEVEL1, spf_type=FORWARD_RUN)
    at spfcomputation.c:748
#1  0x0805ad2f in Compute_and_Store_Forward_SPF (spf_root=0x0, level=LEVEL1) at rlfa.c:172
#2  0x0805fe37 in broadcast_filter_select_pq_nodes_from_ex_pspace (S=0x80b1980, protected_link=0x80c9618,
    level=LEVEL1) at rlfa.c:697
#3  0x0807f2f7 in compute_backup_routine (spf_root=0x80b1980, level=LEVEL1) at spfcomputation.c:731
#4  0x0807f7e9 in spf_computation (spf_root=0x80b1980, spf_info=0x80b4ba4, level=LEVEL1, spf_type=FULL_RUN)
    at spfcomputation.c:781
#5  0x08074ccd in _run_spf_run_all_nodes () at spfclihandler.c:72
#6  0x08074cf0 in run_spf_run_all_nodes (param=0x80a0380 <sync>, tlv_buf=0x80ae030,
    enable_or_disable=OPERATIONAL) at spfclihandler.c:80
#7  0x0808e4f3 in build_tlv_buffer (tokens=0x80ac360 <tokens>, token_cnt=3) at parser.c:232
#8  0x0808e7a1 in parse_input_cmd (input=0x80aaa60 <cons_input_buffer> "run in sy", len=9) at parser.c:310
#9  0x0808e8fc in command_parser () at parser.c:353
#10 0x0808d42b in start_shell () at cmd_hier.c:566
#11 0x08048be7 in main (argc=1, argv=0xbffff144) at testapp.c:83
(gdb)

**Config  :** 
Enable remote backup up calculation
link protected : R1, 0/9
Topology : build_cisco_example_topo()

**Comment by sachinites** [comment]
The fix would be to store the Reverse SPF result in a separate data structure rather than clearing and reusing the Forward SPF run data structure.
